DROP TABLE IF EXISTS model.username;
GO
CREATE TABLE model.username
(
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newsequentialid(),
    login NVARCHAR(20) UNIQUE NOT NULL,
    password NVARCHAR(15) NOT NULL,
    created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP NOT NULL,
);
GO