CREATE TABLE model.username
(
    id UNIQUEIDENTIFIER PRIMARY KEY,
    login VARCHAR(20) NOT NULL,
    password VARCHAR(15) NOT NULL,
    created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP NOT NULL
);